---
hide_body: false
is_partial: false
fields:
- type: text
  label: Title
  name: title
  description: Used for SEO. Fallback for Headline.
  config:
    required: true
- type: text
  name: headline
  label: Page Headline
  description: Optional override for title
- type: textarea
  name: description
  label: Description
  description: Used for SEO
  config:
    required: false
- type: textarea
  name: textline
  label: Page Textline
  description: Optional override for description
- type: image_gallery
  name: images
  label: Images
  description: Used for SEO & Featured Images
- type: list
  name: authors
  label: Authors
  config:
    use_select: true
    source:
      type: datafiles
      file: authors-yml
      path: map
  default: []
- type: list
  name: categories
  label: Categories
  config:
    use_select: true
    source:
      type: simple
    options:
    - CMS
    - Jekyll
    - Hugo
    - Static Sites
    - Static Site Generators
    - Company
    - Frontend-Friday
- type: tag_list
  name: tags
  label: Tags
- type: datetime
  name: publishdate
  label: Publish Date
  description: Date this page should be made public
  config:
    date_format: MMMM DD, YYYY
    time_format: h:mmA
    required: true
  default: 2017-12-07 04:00:00 +0000
- type: datetime
  name: expirydate
  label: Expiry Date
  description: Date this page should be unpublished
  config:
    date_format: MMMM DD, YYYY
    time_format: h:mmA
  default: 2030-01-01 04:00:00 +0000
- type: field_group
  label: Footer Call To Action
  name: cta
  description: Configure the CTA in the page's footer
  fields:
  - type: text
    name: headline
    label: Headline
    description: Optional; defaults will be used if empty
  - type: textarea
    name: textline
    label: Textline
    description: Optional; defaults will be used if empty
  - type: field_group_list
    name: calls_to_action
    label: Calls to Action
    description: Configure buttons/links in the CTA
    fields:
    - type: text
      label: Permalink
      name: permalink
      config:
        required: true
    - type: text
      name: textline
      label: Textline
      hidden: false
      config:
        required: true
    - type: boolean
      name: button
      label: Is button?
    config:
      labelField: textline
- type: boolean
  name: private
  label: Exclude from sitemap?
- type: number
  name: weight
  label: Weight
  description: Used to handle sorting order, menu order, etc.
- type: list
  name: aliases
  label: Aliases
  description: Create page redirects. Put in relative path
  config:
    use_select: false
    source:
      type: datafiles
- type: list
  name: menu
  label: menu
pages:
- hugo/content/terms.md
- hugo/content/docs/troubleshooting
- hugo/content/docs/faqs
- hugo/content/docs/welcome
- hugo/content/docs/_index.md
- hugo/content/docs/changelog
- hugo/content/docs/git-sync
- hugo/content/careers/software-engineer.md
- hugo/content/careers/marketing.md
- hugo/content/careers/full-stack.md
- hugo/content/careers/_index.md
- hugo/content/careers/admin.md
- hugo/content/careers/devrel.md
- hugo/content/blog/bigger-better-editor.md
- hugo/content/blog/new-test.md
- hugo/content/blog/up-and-running-with-hugo.md
- hugo/content/blog/up-and-running-with-hugo-part-2.md
- hugo/content/blog/forestry-gitlab.md
- hugo/content/blog/building-a-company-component-library.md
- hugo/content/blog/why-we-built-forestry.md
- hugo/content/blog/what-s-new-in-jekyll-3-4-0.md
- hugo/content/blog/wysiwyg-formatting-in-front-matter.md
- hugo/content/blog/search-with-algolia-in-hugo.md
- hugo/content/blog/march-27th-service-outage.md
- hugo/content/blog/join-our-slack-community.md
- hugo/content/blog/introducing-media-management.md
- hugo/content/blog/introducing-forestry-config-files.md
- hugo/content/blog/improved-collaboration-and-more.md
- hugo/content/blog/choose-static.md
- hugo/content/blog/hugo-and-jekyll-compared.md
- hugo/content/blog/forestryio-techstars-2016.md
- hugo/content/blog/front-matter-templates.md
- hugo/content/blog/big-improvements-to-front-matter-templates.md
- hugo/content/blog/the-new-forestry-io.md
- hugo/content/blog/search-with-algolia-in-jekyll.md
- hugo/content/blog/_index.md
- hugo/content/blog/discontinuing-zip-sites.md
- hugo/content/blog/layout-improvements.md
- hugo/content/blog/a-hugo-update-everyone-should-be-talking-about.md
- hugo/content/blog/hugo-vs-jekyll-benchmark.md
